FROM pytorch/pytorch:1.11.0-cuda11.3-cudnn8-runtime

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV TOKENIZERS_PARALLELISM=false

EXPOSE 8000

ENTRYPOINT ["uvicorn", "server:app"]